-- Pedidos Clean It · trazabilidad integral de cambios de precios
-- Ejecutar una sola vez en Supabase > SQL Editor.
-- Registra cambios hechos desde Excel y cambios manuales desde la ficha del insumo.

begin;

create table if not exists public.material_price_history(
  id bigint generated by default as identity primary key,
  material_id uuid not null references public.materials(id) on delete cascade,
  material_name_snapshot text,
  sku_snapshot text,
  old_price numeric(14,2) not null check(old_price >= 0),
  new_price numeric(14,2) not null check(new_price >= 0),
  change_method text not null default 'manual',
  source_file text,
  source_sheet text,
  changed_by uuid references public.profiles(id) on delete set null,
  changed_at timestamptz not null default now()
);

alter table public.material_price_history
  add column if not exists material_name_snapshot text,
  add column if not exists change_method text;

update public.material_price_history h
set material_name_snapshot = coalesce(h.material_name_snapshot, m.name),
    change_method = coalesce(
      nullif(h.change_method, ''),
      case when h.source_file is not null then 'excel' else 'manual' end
    )
from public.materials m
where m.id = h.material_id
  and (h.material_name_snapshot is null or h.change_method is null or h.change_method = '');

update public.material_price_history
set change_method = case when source_file is not null then 'excel' else 'manual' end
where change_method is null or change_method = '';

alter table public.material_price_history
  alter column change_method set default 'manual',
  alter column change_method set not null;

create index if not exists idx_material_price_history_material
  on public.material_price_history(material_id, changed_at desc);
create index if not exists idx_material_price_history_changed
  on public.material_price_history(changed_at desc);

alter table public.material_price_history enable row level security;

drop policy if exists material_price_history_admin_read on public.material_price_history;
create policy material_price_history_admin_read
  on public.material_price_history
  for select
  to authenticated
  using(public.is_admin());

revoke all on public.material_price_history from anon;
grant select on public.material_price_history to authenticated;
grant usage, select on sequence public.material_price_history_id_seq to authenticated;

do $$
begin
  if not exists(
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'material_price_history'
  ) then
    alter publication supabase_realtime add table public.material_price_history;
  end if;
end;
$$;

-- El trigger centraliza la auditoría: cualquier actualización real de unit_price queda registrada.
create or replace function public.audit_material_price_change()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
declare
  v_source_file text;
  v_source_sheet text;
  v_change_method text;
begin
  if round(coalesce(old.unit_price, 0), 2) = round(coalesce(new.unit_price, 0), 2) then
    return new;
  end if;

  v_source_file := nullif(current_setting('app.price_source_file', true), '');
  v_source_sheet := nullif(current_setting('app.price_source_sheet', true), '');
  v_change_method := nullif(current_setting('app.price_change_method', true), '');

  insert into public.material_price_history(
    material_id,
    material_name_snapshot,
    sku_snapshot,
    old_price,
    new_price,
    change_method,
    source_file,
    source_sheet,
    changed_by,
    changed_at
  ) values (
    new.id,
    new.name,
    new.sku,
    round(coalesce(old.unit_price, 0), 2),
    round(coalesce(new.unit_price, 0), 2),
    coalesce(v_change_method, case when v_source_file is not null then 'excel' else 'manual' end),
    v_source_file,
    v_source_sheet,
    auth.uid(),
    now()
  );

  return new;
end;
$$;

drop trigger if exists trg_audit_material_price_change on public.materials;
create trigger trg_audit_material_price_change
after update of unit_price on public.materials
for each row
when (old.unit_price is distinct from new.unit_price)
execute function public.audit_material_price_change();

-- Reemplaza la función anterior para que el trigger registre una sola fila por cambio,
-- conservando archivo, hoja, usuario y fecha de la importación.
create or replace function public.admin_bulk_update_material_prices(
  p_updates jsonb,
  p_source_file text default null,
  p_source_sheet text default null
)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  v_item jsonb;
  v_material public.materials%rowtype;
  v_material_id uuid;
  v_expected_sku text;
  v_expected_old_price numeric(14,2);
  v_new_price numeric(14,2);
  v_updated_count integer := 0;
  v_unchanged_count integer := 0;
  v_results jsonb := '[]'::jsonb;
begin
  if not public.is_admin() then
    raise exception 'Solo el administrador puede actualizar precios.';
  end if;

  if p_updates is null or jsonb_typeof(p_updates) <> 'array' then
    raise exception 'La lista de precios a actualizar no es válida.';
  end if;

  if jsonb_array_length(p_updates) < 1 then
    raise exception 'No se recibieron precios para actualizar.';
  end if;

  if jsonb_array_length(p_updates) > 1000 then
    raise exception 'La actualización supera el máximo de 1000 insumos por operación.';
  end if;

  if p_source_file is not null and char_length(p_source_file) > 250 then
    raise exception 'El nombre del archivo es demasiado extenso.';
  end if;

  if p_source_sheet is not null and char_length(p_source_sheet) > 150 then
    raise exception 'El nombre de la hoja es demasiado extenso.';
  end if;

  perform set_config('app.price_change_method', 'excel', true);
  perform set_config('app.price_source_file', coalesce(nullif(btrim(p_source_file), ''), ''), true);
  perform set_config('app.price_source_sheet', coalesce(nullif(btrim(p_source_sheet), ''), ''), true);

  for v_item in select value from jsonb_array_elements(p_updates)
  loop
    begin
      v_material_id := nullif(v_item->>'material_id','')::uuid;
    exception when invalid_text_representation then
      raise exception 'Uno de los identificadores de insumo no es válido.';
    end;

    begin
      v_new_price := round(nullif(v_item->>'new_price','')::numeric, 2);
    exception when invalid_text_representation then
      raise exception 'Uno de los precios nuevos no es válido.';
    end;

    begin
      v_expected_old_price := round(nullif(v_item->>'expected_old_price','')::numeric, 2);
    exception when invalid_text_representation then
      raise exception 'Uno de los precios anteriores no es válido.';
    end;

    v_expected_sku := nullif(btrim(coalesce(v_item->>'sku','')), '');

    if v_material_id is null then
      raise exception 'Falta identificar uno de los insumos.';
    end if;

    if v_new_price is null or v_new_price < 0 or v_new_price > 999999999.99 then
      raise exception 'Uno de los precios nuevos está fuera del rango permitido.';
    end if;

    select * into v_material
    from public.materials
    where id = v_material_id
    for update;

    if not found then
      raise exception 'Uno de los insumos ya no existe. Actualizá los datos y volvé a analizar el archivo.';
    end if;

    if v_expected_sku is not null
       and upper(btrim(coalesce(v_material.sku,''))) <> upper(v_expected_sku) then
      raise exception 'El SKU del insumo % cambió desde que se analizó el archivo. Volvé a analizar la lista.', v_material.name;
    end if;

    if v_expected_old_price is not null
       and abs(round(v_material.unit_price,2) - v_expected_old_price) >= 0.01 then
      raise exception 'El precio de % cambió desde que se analizó el archivo. Volvé a analizar la lista.', v_material.name;
    end if;

    if round(v_material.unit_price,2) = v_new_price then
      v_unchanged_count := v_unchanged_count + 1;
      v_results := v_results || jsonb_build_array(jsonb_build_object(
        'material_id', v_material.id,
        'sku', v_material.sku,
        'old_price', v_material.unit_price,
        'new_price', v_new_price,
        'status', 'sin_cambios'
      ));
      continue;
    end if;

    update public.materials
    set unit_price = v_new_price
    where id = v_material.id;

    v_updated_count := v_updated_count + 1;
    v_results := v_results || jsonb_build_array(jsonb_build_object(
      'material_id', v_material.id,
      'sku', v_material.sku,
      'old_price', round(v_material.unit_price,2),
      'new_price', v_new_price,
      'status', 'actualizado'
    ));
  end loop;

  return jsonb_build_object(
    'updated_count', v_updated_count,
    'unchanged_count', v_unchanged_count,
    'results', v_results
  );
end;
$$;

revoke all on function public.admin_bulk_update_material_prices(jsonb,text,text) from public;
grant execute on function public.admin_bulk_update_material_prices(jsonb,text,text) to authenticated;

commit;

notify pgrst, 'reload schema';
