-- Pedidos Clean It · importación masiva de precios desde Excel
-- Ejecutar una sola vez en Supabase > SQL Editor.
-- No modifica pedidos históricos ni precios congelados en order_items.

begin;

create table if not exists public.material_price_history(
  id bigint generated by default as identity primary key,
  material_id uuid not null references public.materials(id) on delete cascade,
  sku_snapshot text,
  old_price numeric(14,2) not null check(old_price >= 0),
  new_price numeric(14,2) not null check(new_price >= 0),
  source_file text,
  source_sheet text,
  changed_by uuid references public.profiles(id) on delete set null,
  changed_at timestamptz not null default now()
);

create index if not exists idx_material_price_history_material
  on public.material_price_history(material_id, changed_at desc);
create index if not exists idx_material_price_history_changed
  on public.material_price_history(changed_at desc);

alter table public.material_price_history enable row level security;

drop policy if exists material_price_history_admin_read on public.material_price_history;
create policy material_price_history_admin_read
  on public.material_price_history
  for select
  to authenticated
  using(public.is_admin());

revoke all on public.material_price_history from anon;
grant select on public.material_price_history to authenticated;
grant usage, select on sequence public.material_price_history_id_seq to authenticated;

create or replace function public.admin_bulk_update_material_prices(
  p_updates jsonb,
  p_source_file text default null,
  p_source_sheet text default null
)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  v_item jsonb;
  v_material public.materials%rowtype;
  v_material_id uuid;
  v_expected_sku text;
  v_expected_old_price numeric(14,2);
  v_new_price numeric(14,2);
  v_updated_count integer := 0;
  v_unchanged_count integer := 0;
  v_results jsonb := '[]'::jsonb;
begin
  if not public.is_admin() then
    raise exception 'Solo el administrador puede actualizar precios.';
  end if;

  if p_updates is null or jsonb_typeof(p_updates) <> 'array' then
    raise exception 'La lista de precios a actualizar no es válida.';
  end if;

  if jsonb_array_length(p_updates) < 1 then
    raise exception 'No se recibieron precios para actualizar.';
  end if;

  if jsonb_array_length(p_updates) > 1000 then
    raise exception 'La actualización supera el máximo de 1000 insumos por operación.';
  end if;

  if p_source_file is not null and char_length(p_source_file) > 250 then
    raise exception 'El nombre del archivo es demasiado extenso.';
  end if;

  if p_source_sheet is not null and char_length(p_source_sheet) > 150 then
    raise exception 'El nombre de la hoja es demasiado extenso.';
  end if;

  for v_item in select value from jsonb_array_elements(p_updates)
  loop
    begin
      v_material_id := nullif(v_item->>'material_id','')::uuid;
    exception when invalid_text_representation then
      raise exception 'Uno de los identificadores de insumo no es válido.';
    end;

    begin
      v_new_price := round(nullif(v_item->>'new_price','')::numeric, 2);
    exception when invalid_text_representation then
      raise exception 'Uno de los precios nuevos no es válido.';
    end;

    begin
      v_expected_old_price := round(nullif(v_item->>'expected_old_price','')::numeric, 2);
    exception when invalid_text_representation then
      raise exception 'Uno de los precios anteriores no es válido.';
    end;

    v_expected_sku := nullif(btrim(coalesce(v_item->>'sku','')), '');

    if v_material_id is null then
      raise exception 'Falta identificar uno de los insumos.';
    end if;

    if v_new_price is null or v_new_price < 0 or v_new_price > 999999999.99 then
      raise exception 'Uno de los precios nuevos está fuera del rango permitido.';
    end if;

    select * into v_material
    from public.materials
    where id = v_material_id
    for update;

    if not found then
      raise exception 'Uno de los insumos ya no existe. Actualizá los datos y volvé a analizar el archivo.';
    end if;

    if v_expected_sku is not null
       and upper(btrim(coalesce(v_material.sku,''))) <> upper(v_expected_sku) then
      raise exception 'El SKU del insumo % cambió desde que se analizó el archivo. Volvé a analizar la lista.', v_material.name;
    end if;

    if v_expected_old_price is not null
       and abs(round(v_material.unit_price,2) - v_expected_old_price) >= 0.01 then
      raise exception 'El precio de % cambió desde que se analizó el archivo. Volvé a analizar la lista.', v_material.name;
    end if;

    if round(v_material.unit_price,2) = v_new_price then
      v_unchanged_count := v_unchanged_count + 1;
      v_results := v_results || jsonb_build_array(jsonb_build_object(
        'material_id', v_material.id,
        'sku', v_material.sku,
        'old_price', v_material.unit_price,
        'new_price', v_new_price,
        'status', 'sin_cambios'
      ));
      continue;
    end if;

    insert into public.material_price_history(
      material_id, sku_snapshot, old_price, new_price,
      source_file, source_sheet, changed_by
    ) values(
      v_material.id, v_material.sku, round(v_material.unit_price,2), v_new_price,
      nullif(btrim(coalesce(p_source_file,'')),''),
      nullif(btrim(coalesce(p_source_sheet,'')),''),
      auth.uid()
    );

    update public.materials
    set unit_price = v_new_price
    where id = v_material.id;

    v_updated_count := v_updated_count + 1;
    v_results := v_results || jsonb_build_array(jsonb_build_object(
      'material_id', v_material.id,
      'sku', v_material.sku,
      'old_price', round(v_material.unit_price,2),
      'new_price', v_new_price,
      'status', 'actualizado'
    ));
  end loop;

  return jsonb_build_object(
    'updated_count', v_updated_count,
    'unchanged_count', v_unchanged_count,
    'results', v_results
  );
end;
$$;

revoke all on function public.admin_bulk_update_material_prices(jsonb,text,text) from public;
grant execute on function public.admin_bulk_update_material_prices(jsonb,text,text) to authenticated;

commit;
