-- Pedidos Clean It · esquema Supabase v4
-- Ejecutar completo en Supabase > SQL Editor sobre un proyecto nuevo.
-- La aplicación pública usa únicamente funciones RPC seguras; no expone las tablas al rol anon.

create extension if not exists pgcrypto;
create sequence if not exists public.order_code_seq start with 1;

create table if not exists public.services(
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  address text,
  description text,
  notes text,
  zone text,
  supervisor text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.materials(
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  name text not null,
  category text not null,
  detail text,
  unit text not null default 'unidad',
  image_url text,
  suggested_quantity numeric(12,2) not null default 1 check(suggested_quantity > 0 and suggested_quantity <= 999),
  sort_order integer not null default 100,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Una fila representa que un insumo está oculto para un servicio.
-- La ausencia de fila significa visible, por lo que todos los insumos quedan habilitados por defecto.
create table if not exists public.service_material_exclusions(
  service_id uuid not null references public.services(id) on delete cascade,
  material_id uuid not null references public.materials(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key(service_id,material_id)
);

create table if not exists public.profiles(
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  full_name text,
  role text not null default 'operator' check(role in('admin','supplier','operator')),
  service_id uuid references public.services(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.orders(
  id uuid primary key default gen_random_uuid(),
  order_code text not null unique default ('PED-' || lpad(nextval('public.order_code_seq')::text,6,'0')),
  service_id uuid not null references public.services(id) on delete restrict,
  reporter_name text not null check(char_length(btrim(reporter_name)) between 2 and 100),
  priority text not null default 'normal' check(priority in('normal','urgente')),
  status text not null default 'pendiente' check(status in('pendiente','preparacion','enviado','entregado','cancelado')),
  notes text check(notes is null or char_length(notes) <= 500),
  total_items integer not null default 0 check(total_items >= 0),
  total_units numeric(14,2) not null default 0 check(total_units >= 0),
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  closed_at timestamptz
);

create table if not exists public.order_items(
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  material_id uuid references public.materials(id) on delete set null,
  item_name text not null,
  category text,
  unit text not null default 'unidad',
  quantity numeric(12,2) not null check(quantity > 0 and quantity <= 999),
  notes text check(notes is null or char_length(notes) <= 300),
  image_url text,
  is_custom boolean not null default false,
  sort_order integer not null default 100,
  created_at timestamptz not null default now()
);

create table if not exists public.order_status_history(
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  old_status text,
  new_status text not null,
  changed_by uuid references public.profiles(id) on delete set null,
  notes text,
  changed_at timestamptz not null default now()
);

create index if not exists idx_service_material_exclusions_material on public.service_material_exclusions(material_id);
create index if not exists idx_profiles_service on public.profiles(service_id);
create index if not exists idx_orders_service on public.orders(service_id);
create index if not exists idx_orders_status on public.orders(status);
create index if not exists idx_orders_priority on public.orders(priority);
create index if not exists idx_orders_created on public.orders(created_at desc);
create index if not exists idx_order_items_order on public.order_items(order_id);
create index if not exists idx_order_history_order on public.order_status_history(order_id);
create index if not exists idx_order_history_changed on public.order_status_history(changed_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists services_set_updated_at on public.services;
create trigger services_set_updated_at before update on public.services for each row execute function public.set_updated_at();
drop trigger if exists materials_set_updated_at on public.materials;
create trigger materials_set_updated_at before update on public.materials for each row execute function public.set_updated_at();
drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at before update on public.profiles for each row execute function public.set_updated_at();
drop trigger if exists orders_set_updated_at on public.orders;
create trigger orders_set_updated_at before update on public.orders for each row execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
begin
  insert into public.profiles(id,email,full_name,role)
  values(new.id,new.email,coalesce(new.raw_user_meta_data->>'full_name',split_part(new.email,'@',1)),'operator')
  on conflict(id) do update set email=excluded.email;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert or update of email on auth.users for each row execute function public.handle_new_user();

insert into public.profiles(id,email,full_name,role)
select id,email,coalesce(raw_user_meta_data->>'full_name',split_part(email,'@',1)),'operator'
from auth.users
on conflict(id) do update set email=excluded.email;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path=public
as $$
  select exists(select 1 from public.profiles where id=auth.uid() and role='admin');
$$;

create or replace function public.is_staff()
returns boolean
language sql
stable
security definer
set search_path=public
as $$
  select exists(select 1 from public.profiles where id=auth.uid() and role in('admin','supplier'));
$$;

create or replace function public.staff_update_order_status(
  p_order_id uuid,
  p_status text,
  p_notes text default null
)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  v_order public.orders%rowtype;
begin
  if not public.is_staff() then
    raise exception 'No tenés permisos para cambiar estados de pedidos.';
  end if;

  if p_status not in('pendiente','preparacion','enviado','entregado','cancelado') then
    raise exception 'El estado indicado no es válido.';
  end if;

  update public.orders
  set status=p_status
  where id=p_order_id
  returning * into v_order;

  if not found then
    raise exception 'El pedido no existe.';
  end if;

  if p_notes is not null and btrim(p_notes) <> '' then
    insert into public.order_status_history(order_id,old_status,new_status,changed_by,notes)
    values(v_order.id,null,v_order.status,auth.uid(),left(btrim(p_notes),300));
  end if;

  return jsonb_build_object(
    'id',v_order.id,
    'order_code',v_order.order_code,
    'status',v_order.status,
    'updated_at',v_order.updated_at,
    'closed_at',v_order.closed_at
  );
end;
$$;

-- Reemplazo atómico del catálogo oculto de un servicio.
create or replace function public.admin_set_service_hidden_materials(
  p_service_id uuid,
  p_hidden_material_ids uuid[]
)
returns integer
language plpgsql
security definer
set search_path=public
as $$
declare
  v_count integer;
begin
  if not public.is_admin() then
    raise exception 'No tenés permisos de administrador.';
  end if;
  if not exists(select 1 from public.services where id=p_service_id) then
    raise exception 'El servicio no existe.';
  end if;

  delete from public.service_material_exclusions where service_id=p_service_id;

  insert into public.service_material_exclusions(service_id,material_id)
  select p_service_id,m.id
  from public.materials m
  where m.id=any(coalesce(p_hidden_material_ids,array[]::uuid[]))
  on conflict(service_id,material_id) do nothing;

  get diagnostics v_count = row_count;
  return v_count;
end;
$$;

create or replace function public.prepare_order_status()
returns trigger
language plpgsql
as $$
begin
  if new.status in ('entregado','cancelado') and (old.status is distinct from new.status or old.closed_at is null) then
    new.closed_at = now();
  elsif new.status not in ('entregado','cancelado') then
    new.closed_at = null;
  end if;
  return new;
end;
$$;

drop trigger if exists orders_prepare_status on public.orders;
create trigger orders_prepare_status before update on public.orders for each row execute function public.prepare_order_status();

create or replace function public.audit_order_status()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
begin
  if tg_op='INSERT' then
    insert into public.order_status_history(order_id,old_status,new_status,changed_by,notes)
    values(new.id,null,new.status,auth.uid(),'Pedido creado');
  elsif old.status is distinct from new.status then
    insert into public.order_status_history(order_id,old_status,new_status,changed_by)
    values(new.id,old.status,new.status,auth.uid());
  end if;
  return new;
end;
$$;

drop trigger if exists orders_status_audit on public.orders;
create trigger orders_status_audit after insert or update of status on public.orders for each row execute function public.audit_order_status();

alter table public.services enable row level security;
alter table public.materials enable row level security;
alter table public.service_material_exclusions enable row level security;
alter table public.profiles enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.order_status_history enable row level security;

drop policy if exists services_admin_read on public.services;
drop policy if exists services_admin_write on public.services;
drop policy if exists services_staff_read on public.services;
drop policy if exists services_admin_all on public.services;
create policy services_staff_read on public.services for select to authenticated using(public.is_staff());
create policy services_admin_all on public.services for all to authenticated using(public.is_admin()) with check(public.is_admin());

drop policy if exists materials_admin_read on public.materials;
drop policy if exists materials_admin_write on public.materials;
drop policy if exists materials_staff_read on public.materials;
drop policy if exists materials_admin_all on public.materials;
create policy materials_staff_read on public.materials for select to authenticated using(public.is_staff());
create policy materials_admin_all on public.materials for all to authenticated using(public.is_admin()) with check(public.is_admin());

drop policy if exists service_material_exclusions_admin_all on public.service_material_exclusions;
drop policy if exists service_material_exclusions_staff_read on public.service_material_exclusions;
drop policy if exists service_material_exclusions_admin_all_v2 on public.service_material_exclusions;
create policy service_material_exclusions_staff_read on public.service_material_exclusions for select to authenticated using(public.is_staff());
create policy service_material_exclusions_admin_all_v2 on public.service_material_exclusions for all to authenticated using(public.is_admin()) with check(public.is_admin());

drop policy if exists profiles_self_admin_read on public.profiles;
drop policy if exists profiles_admin_update on public.profiles;
drop policy if exists profiles_staff_read on public.profiles;
drop policy if exists profiles_admin_update_v2 on public.profiles;
create policy profiles_staff_read on public.profiles for select to authenticated using(id=auth.uid() or public.is_staff());
create policy profiles_admin_update_v2 on public.profiles for update to authenticated using(public.is_admin()) with check(public.is_admin());

drop policy if exists orders_admin_all on public.orders;
drop policy if exists orders_staff_read on public.orders;
drop policy if exists orders_admin_all_v2 on public.orders;
create policy orders_staff_read on public.orders for select to authenticated using(public.is_staff());
create policy orders_admin_all_v2 on public.orders for all to authenticated using(public.is_admin()) with check(public.is_admin());

drop policy if exists order_items_admin_all on public.order_items;
drop policy if exists order_items_staff_read on public.order_items;
drop policy if exists order_items_admin_all_v2 on public.order_items;
create policy order_items_staff_read on public.order_items for select to authenticated using(public.is_staff());
create policy order_items_admin_all_v2 on public.order_items for all to authenticated using(public.is_admin()) with check(public.is_admin());

drop policy if exists order_history_admin_read on public.order_status_history;
drop policy if exists order_history_staff_read on public.order_status_history;
create policy order_history_staff_read on public.order_status_history for select to authenticated using(public.is_staff());

-- Lectura pública controlada del selector y catálogo.
create or replace function public.public_order_bootstrap()
returns jsonb
language sql
stable
security definer
set search_path=public
as $$
  select jsonb_build_object(
    'services', coalesce((
      select jsonb_agg(to_jsonb(s) order by s.name)
      from (
        select id,name,address,description,zone,supervisor,active
        from public.services
        where active=true
      ) s
    ), '[]'::jsonb),
    'materials', coalesce((
      select jsonb_agg(to_jsonb(m) order by m.category,m.sort_order,m.name)
      from (
        select id,slug,name,category,detail,unit,image_url,suggested_quantity,sort_order,active
        from public.materials
        where active=true
      ) m
    ), '[]'::jsonb),
    'hidden_materials', coalesce((
      select jsonb_agg(jsonb_build_object('service_id',x.service_id,'material_id',x.material_id))
      from public.service_material_exclusions x
      join public.services s on s.id=x.service_id and s.active=true
      join public.materials m on m.id=x.material_id and m.active=true
    ), '[]'::jsonb)
  );
$$;

-- Alta pública de pedidos. El rol anon no recibe acceso directo a ninguna tabla.
create or replace function public.public_create_order(
  p_service_id uuid,
  p_reporter_name text,
  p_priority text,
  p_notes text,
  p_items jsonb
)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  v_order public.orders%rowtype;
  v_item jsonb;
  v_material public.materials%rowtype;
  v_material_id uuid;
  v_quantity numeric(12,2);
  v_custom_name text;
  v_unit text;
  v_item_notes text;
  v_count integer := 0;
  v_total numeric(14,2) := 0;
begin
  if not exists(select 1 from public.services where id=p_service_id and active=true) then
    raise exception 'El servicio seleccionado no existe o está inactivo.';
  end if;

  if char_length(btrim(coalesce(p_reporter_name,''))) not between 2 and 100 then
    raise exception 'Ingresá un nombre válido.';
  end if;

  if coalesce(p_priority,'normal') not in ('normal','urgente') then
    raise exception 'La prioridad no es válida.';
  end if;

  if p_notes is not null and char_length(p_notes) > 500 then
    raise exception 'La observación general es demasiado extensa.';
  end if;

  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) < 1 then
    raise exception 'El pedido debe incluir al menos un insumo.';
  end if;

  if jsonb_array_length(p_items) > 80 then
    raise exception 'El pedido supera el máximo de 80 ítems.';
  end if;

  insert into public.orders(service_id,reporter_name,priority,notes,created_by)
  values(p_service_id,btrim(p_reporter_name),coalesce(p_priority,'normal'),nullif(btrim(coalesce(p_notes,'')),''),auth.uid())
  returning * into v_order;

  for v_item in select value from jsonb_array_elements(p_items)
  loop
    v_quantity := nullif(v_item->>'quantity','')::numeric;
    if v_quantity is null or v_quantity <= 0 or v_quantity > 999 then
      raise exception 'Una de las cantidades no es válida.';
    end if;

    v_material_id := null;
    if nullif(v_item->>'material_id','') is not null then
      begin
        v_material_id := (v_item->>'material_id')::uuid;
      exception when invalid_text_representation then
        raise exception 'Uno de los insumos no es válido.';
      end;
    end if;

    if v_material_id is not null then
      select * into v_material from public.materials where id=v_material_id and active=true;
      if not found then
        raise exception 'Uno de los insumos ya no está disponible.';
      end if;

      if exists(
        select 1 from public.service_material_exclusions
        where service_id=p_service_id and material_id=v_material_id
      ) then
        raise exception 'Uno de los insumos no está habilitado para este servicio.';
      end if;

      insert into public.order_items(order_id,material_id,item_name,category,unit,quantity,notes,image_url,is_custom,sort_order)
      values(v_order.id,v_material.id,v_material.name,v_material.category,v_material.unit,v_quantity,null,v_material.image_url,false,v_material.sort_order);
    else
      v_custom_name := btrim(coalesce(v_item->>'custom_name',''));
      v_unit := btrim(coalesce(v_item->>'unit','unidad'));
      v_item_notes := nullif(btrim(coalesce(v_item->>'notes','')),'');

      if char_length(v_custom_name) not between 2 and 120 then
        raise exception 'El nombre del insumo no listado no es válido.';
      end if;
      if char_length(v_unit) not between 1 and 60 then
        raise exception 'La unidad del insumo no listado no es válida.';
      end if;
      if v_item_notes is not null and char_length(v_item_notes) > 300 then
        raise exception 'El detalle del insumo no listado es demasiado extenso.';
      end if;

      insert into public.order_items(order_id,material_id,item_name,category,unit,quantity,notes,image_url,is_custom,sort_order)
      values(v_order.id,null,v_custom_name,'Excepción',v_unit,v_quantity,v_item_notes,'assets/materials/default.svg',true,9999);
    end if;

    v_count := v_count + 1;
    v_total := v_total + v_quantity;
  end loop;

  update public.orders
  set total_items=v_count,total_units=v_total
  where id=v_order.id
  returning * into v_order;

  return jsonb_build_object(
    'id',v_order.id,
    'order_code',v_order.order_code,
    'created_at',v_order.created_at,
    'item_count',v_order.total_items,
    'total_units',v_order.total_units
  );
exception when others then
  raise;
end;
$$;

revoke all on public.services, public.materials, public.service_material_exclusions, public.profiles, public.orders, public.order_items, public.order_status_history from anon;
grant select,insert,update,delete on public.services, public.materials, public.service_material_exclusions, public.profiles, public.orders, public.order_items, public.order_status_history to authenticated;
grant usage,select on all sequences in schema public to authenticated;
grant execute on function public.public_order_bootstrap() to anon,authenticated;
grant execute on function public.public_create_order(uuid,text,text,text,jsonb) to anon,authenticated;
revoke all on function public.staff_update_order_status(uuid,text,text) from public;
grant execute on function public.staff_update_order_status(uuid,text,text) to authenticated;
revoke all on function public.admin_set_service_hidden_materials(uuid,uuid[]) from public;
grant execute on function public.admin_set_service_hidden_materials(uuid,uuid[]) to authenticated;

-- Bucket público para imágenes cargadas desde Administración.
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values('material-images','material-images',true,5242880,array['image/png','image/jpeg','image/webp','image/svg+xml'])
on conflict(id) do update set public=excluded.public,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;

drop policy if exists material_images_public_read on storage.objects;
drop policy if exists material_images_admin_insert on storage.objects;
drop policy if exists material_images_admin_update on storage.objects;
drop policy if exists material_images_admin_delete on storage.objects;
create policy material_images_public_read on storage.objects for select using(bucket_id='material-images');
create policy material_images_admin_insert on storage.objects for insert to authenticated with check(bucket_id='material-images' and public.is_admin());
create policy material_images_admin_update on storage.objects for update to authenticated using(bucket_id='material-images' and public.is_admin()) with check(bucket_id='material-images' and public.is_admin());
create policy material_images_admin_delete on storage.objects for delete to authenticated using(bucket_id='material-images' and public.is_admin());

-- Realtime para el panel administrativo.
do $$
declare
  v_table text;
begin
  foreach v_table in array array['orders','order_items','order_status_history','materials','services','service_material_exclusions','profiles']
  loop
    if not exists(
      select 1 from pg_publication_tables
      where pubname='supabase_realtime' and schemaname='public' and tablename=v_table
    ) then
      execute format('alter publication supabase_realtime add table public.%I',v_table);
    end if;
  end loop;
end;
$$;

-- Datos iniciales

insert into public.services(name,address,description,notes,zone,supervisor,active) values
  ('Alvarez Thomas 550- Colegiales','Alvarez Thomas 550','Lunes a viernes de 13 a 17 hs. Sábado de 8 a 12 hs.',null,'Colegiales','José',true),
  ('America Tampas- P.Industrial Pilar','Parque industrial, C. 9 1761, B1629 Pilar','Lunes a viernes de 8 a 16 hs. Sábado de 8 a 12 hs.',null,'Pilar','José',true),
  ('Av De los Incas 3502','Av De los Incas 3502','Lunes, miércoles y viernes de 13 a 17 hs.',null,'Belgrano','José',true),
  ('Av MITRE 5834 - Caseros','Av MITRE 5834 - Caseros','Lunes, miércoles y viernes de 7:30 a 11:30 hs.',null,'Caseros','Andres',true),
  ('Av. San Juan 440','Av. San Juan 440','Martes, jueves y sábado de 8 a 12 hs.',null,'San Telmo',null,true),
  ('Callao 441 - Centro','Callao 441 - Centro','Lunes a viernes de 13 a 17 hs.',null,'Centro','Leo',true),
  ('Ceretti 2161 - Villa Urquiza','Ceretti 2161','Lunes a sábados de 8 a 12 hs.',null,'Villa Urquiza','Jose',true),
  ('Céspedes 2524, CABA','Céspedes 2524 - Adm Holmberg/Cespedes - Fernando','Lunes a viernes de 8 a 12 hs.',null,'Colegiales','José',true),
  ('cons Cabildo 2659','Cabildo 2659','Lunes a viernes de 13 a 16 hs.',null,'Belgrano','José',true),
  ('Cons. Agrelo 3641- Boedo','Agrelo 3641','Lunes, miércoles y viernes de 11:30 a 13:30 hs.',null,'Boedo',null,true),
  ('Cons. Araujo 61-Villa Luro','Araujo 61','Lunes, miércoles y viernes de 9 a 12 hs.',null,'Villa Luro',null,true),
  ('Cons. Av Directorio 1821','Av Directorio 1821','Viernes de 12:30 a 15:30 hs.',null,'Flores',null,true),
  ('Cons. Av Los Incas 3501','Av Los Incas 3501','Lunes a sábados de 8 a 12 hs.',null,'Belgrano R','Jose',true),
  ('Cons. Beiro 4545- Villa Devoto','Avenida Beiro 4545','Lunes a sábados de 8:30 a 12:30 hs.','Lunes a sábados 8:30 a 12:30','Villa Devoto','Jose',true),
  ('Cons. Cabildo 2737- Nuñez','Cabildo 2737','Lunes a viernes de 8 a 12 hs.',null,'Nuñez','Jose',true),
  ('Cons. Cachimayo 748- Parque Chacabuco','Cachimayo 748','Lunes a sábados de 8 a 12 hs.',null,'Parque Chacabuco',null,true),
  ('Cons. Catamarca 586- San Cristóbal','Catamarca 586','Lunes, miércoles y viernes de 13 a 16 hs.',null,'San Cristóbal',null,true),
  ('Cons. Cnel Diaz 1450','Coronel Diaz 1450','Lunes, miércoles y viernes de 8 a 12 hs.',null,'Recoleta/Palermo','Jose',true),
  ('Cons. Darwin 524- Villa Crespo','Darwin 524','Martes, jueves y sábado de 8 a 12 hs.',null,'Villa Crespo','José',true),
  ('Cons. Gualeguaychú 1938- Villa Devoto','Gualeguaychú 1938','Martes, jueves y sábado de 8 a 12 hs.',null,'Villa Devoto','Leo',true),
  ('Cons. Gualeguaychú 3809/11 caba','Gualeguaychú 3809','Martes y jueves de 8 a 11 hs.',null,'Villa Devoto','Jose',true),
  ('Cons. Guardia Vieja 3919-Villa Crespo','Guardia Vieja 3919','Martes y sábado de 8 a 12 hs.',null,'Villa Crespo','Jose',true),
  ('Cons. Hipólito Yrigoyen 3132- Once','Hipólito Yrigoyen 3132','Martes y jueves de 13 a 17 hs. Sábado de 8 a 12 hs.',null,'Once',null,true),
  ('Cons. Jose Hernández 2678- Belgrano','Jose Hernández 2678','Lunes y viernes de 8 a 11 hs.',null,'Belgrano','Jose',true),
  ('Cons. José Marmol 2134 CABA','José Marmol 2134','Lunes, miércoles y viernes de 8 a 12 hs.',null,'Boedo',null,true),
  ('Cons. Juian Álvarez 1340- Villa Crespo','Julian Álvarez 1340','Martes y jueves de 7 a 12 hs. Sábado de 7 a 13 hs.',null,'Villa Crespo',null,true),
  ('Cons. Juncal 2899','Juncal 2899','Lunes a sábados de 8 a 12 hs.',null,'Palermo','Jose',true),
  ('Cons. Lascano 4032','Lascano 4032','Miércoles y sábado de 8 a 12 hs.',null,'Monte Castro',null,true),
  ('Cons. Lezica 4475','Lezica 4475','Lunes a sábados de 8 a 12 hs.',null,'Almagro','Leonardo',true),
  ('Cons. Luis M Campos 1027','Luis M Campos 1027','Lunes a viernes de 8 a 14 hs. Sábado de 8 a 12 hs.',null,'Palermo','Jose',true),
  ('Cons. Manzanares 1753','Manzanares 1753','Martes, jueves y sábado de 13 a 17 hs.',null,'Nuñez','José',true),
  ('Cons. Migueletes 1762','Migueletes 1762','Martes, jueves y sábado de 8 a 12 hs.',null,'Belgrano','Jose',true),
  ('Cons. MIRABILA Humboldt 2045 CABA','Humboldt 2045','Sin cobertura activa informada en el archivo.',null,'Palermo','Jose/Leo',true),
  ('Cons. Moldes 1648- Nuñez','Moldes 1648','Lunes, miércoles y viernes de 8 a 12 hs.',null,'Nuñez','Jose',true),
  ('Cons. Olagüer y Feliu 2970- Colegiales','Olagüer y Feliu 2970','Lunes a sábados de 13 a 16 hs.',null,'Colegiales','Jose',true),
  ('Cons. Plaza 3547- Coghlan','Plaza 3547','Martes y viernes de 16 a 19 hs.',null,'Coghlan','Jose',true),
  ('Cons. Puan 256/60- Caballito','Puan 256/60','Martes, jueves y sábado de 8 a 12 hs.',null,'Caballito',null,true),
  ('Cons. Rivadavia 9037-Floresta','Rivadavia 9037','Martes, jueves y sábado de 8 a 12 hs.',null,'Floresta',null,true),
  ('Cons. Roosevelt 1926- Belgrano','Roosevelt 1926','Lunes, miércoles y viernes de 8 a 12 hs.',null,'Belgrano','Jose',true),
  ('Cons.Aristobulo del Valle 1301-La Boca.','Aristobulo del Valle 1301','Lunes a viernes de 8 a 16 hs. Sábado de 8 a 12 hs.',null,'La Boca',null,true),
  ('Cons.Ciudad de la Paz 575','Ciudad de la Paz 575','Martes, jueves y sábado de 8 a 12 hs.',null,'Palermo','Jose',true),
  ('Cons.Palacio Cabrera 5356- Palermo','Cabrera 5356','Lunes a viernes de 8 a 14 hs. Sábado de 8 a 12 hs.',null,'Palermo','Jose',true),
  ('Cons.Thomas Le Bretón 5153 - Villa Urquiza','Le Bretón 5153','Martes, jueves y sábado de 8 a 12 hs.',null,'Villa Urquiza','Jose',true),
  ('Florentino Ameghino 680','Florentino Ameghino 680','Lunes, miércoles y viernes de 12 a 16 hs.',null,'Parque Avellaneda',null,true),
  ('Gym Formosa 168- Parque Chacabuco','Formosa 168','Martes y jueves de 13 a 17 hs.',null,'Parque Chacabuco',null,true),
  ('Holmberg 4150 - Saavedra','Holmberg 4150','Miércoles y viernes de 13 a 17 hs.',null,'Saavedra','Jose',true),
  ('ISEM SA','Emilio Mitre 1970','Lunes, miércoles y jueves de 12:30 a 16:30 hs.','DE BAJA','Parque Chacabuco',null,true),
  ('Laboratorio Eurolab -Juan de Garay 3831-Boedo','Juan de Garay 3831','Lunes a viernes de 8 a 11 hs.',null,'Boedo',null,true),
  ('Ludoplast Caseros LEONISMO ARGENTINO 3264 -CASEROS','LEONISMO ARGENTINO 3264','Lunes, miércoles y viernes de 8 a 12 hs.',null,'CASEROS','Jose',true),
  ('Martinez castro 263','Martinez castro 263','Lunes y miércoles de 9 a 12 hs. Viernes de 8 a 12 hs.',null,'Velez Sarfield',null,true),
  ('Molycentro - A- Lamas 2135- V- Crespo','Andres Lamas 2135','Lunes, miércoles y viernes de 8 a 12 hs.',null,'Villa Crespo',null,true),
  ('Molysil Avellaneda - Catamarca 1856','Catamarca 1856','Martes y jueves de 12 a 17 hs.',null,'Avellaneda',null,true),
  ('Molysil- Olagüer y Feliü 3398 Colegiales','Olagüer y Feliü 3398','Martes y jueves de 7:30 a 11:30 hs.',null,'Colegiales','Jose',true),
  ('Monteagudo 121 Ramos Mejia','Monteagudo 121 Ramos Mejia - Adrián Palumbo','Lunes a sábados de 13 a 19 hs.',null,'Ramos Mejía','José',true),
  ('mundo chipa','Estrada 1859, villa maipú','Lunes a viernes de 13 a 17 hs.',null,'villa maipú','Jose',true),
  ('Oficina Av Cordoba 1309','Av Cordoba 1309','Lunes, miércoles y viernes de 14 a 18 hs. Martes y jueves de 16 a 18 hs.',null,'Retiro',null,true),
  ('Oficina Naon Casa Central','Naon 3475','Lunes, miércoles y viernes de 12:30 a 16:30 hs.',null,'Coghlan','Jose/Leo',true),
  ('Pergamino 160','Pergamino 160','Lunes, miércoles y viernes de 8 a 12 hs.',null,'Floresta',null,true),
  ('Peru 1566','Peru 1566','Sin cobertura activa informada en el archivo.','BAJA A PARTIR DEL 5/6','San Telmo',null,true),
  ('Serv Warnes 1243 caba','Warnes 1243','Lunes, miércoles y viernes de 8 a 13 hs.',null,'Villa Crespo','Jose',true),
  ('sp . Vte López. Libertad 1650','Libertad 1650','Lunes a viernes de 7 a 15 hs. Sábado de 9 a 13 hs.',null,'Vicente Lopez','Jose',true),
  ('SP Const - Pueyrredón','Av. de los Constituyentes 6020','Lunes a viernes de 9 a 13 y 17 a 22 hs. Sábado de 10 a 14 hs.',null,'Villa Pueyrredón','Jose',true),
  ('Spital Hnos','COLECTORA, Acceso Sudeste KM. 12, Los Ciruelos 3748, B1874 Sarandí','Lunes, martes, miércoles y viernes de 9 a 14 hs. Jueves de 9 a 13 hs.','BAJA','Sarandí','Leonardo',true),
  ('Virrey Olaguer y Feliu 2453 CABA','Virrey Olaguer y Feliu 2453 - Kestelboim','Lunes a sábados de 8 a 12 hs.',null,'Colegiales','José',true)
on conflict(name) do update set address=excluded.address,description=excluded.description,notes=excluded.notes,zone=excluded.zone,supervisor=excluded.supervisor,active=excluded.active;

insert into public.materials(slug,name,category,detail,unit,image_url,suggested_quantity,sort_order,active) values
  ('detergente-bio-ultra','Detergente ultraconcentrado','Químicos','Bio Ultra - Thames · bidón x 5 Lts','bidón x 5 Lts','assets/materials/detergente-bio-ultra.svg',1.0,10,true),
  ('perfume-flower','Perfume o aromatizante de piso','Químicos','Flower - Thames · bidón x 5 Lts','bidón x 5 Lts','assets/materials/perfume-flower.svg',1.0,20,true),
  ('lavandina-bio-lav','Lavandina líquida desinfectante','Químicos','Bio Lav - Thames · bidón x 5 Lts','bidón x 5 Lts','assets/materials/lavandina-bio-lav.svg',1.0,30,true),
  ('rapid-plus-gel','Lavandina en gel desinfectante','Químicos','Rapid Plus en gel - Thames · 500 ml','envase x 500 ml','assets/materials/rapid-plus-gel.svg',1.0,40,true),
  ('wood-thames','Wood','Químicos','Thames · 360 cm3','envase x 360 cm3','assets/materials/wood-thames.svg',1.0,50,true),
  ('steel-shine','Steel Shine','Químicos','Thames · 390 cm3','aerosol x 390 cm3','assets/materials/steel-shine.svg',1.0,60,true),
  ('cream-thames','Cream','Químicos','Thames · 500 ml','envase x 500 ml','assets/materials/cream-thames.svg',1.0,70,true),
  ('sarro-attack','Sarro Attack','Químicos','Thames · 500 ml','envase x 500 ml','assets/materials/sarro-attack.svg',1.0,80,true),
  ('smell-thames','Smell o aromatizante ambiental','Químicos','Thames · 262 ml','envase x 262 ml','assets/materials/smell-thames.svg',3.0,90,true),
  ('alcohol-al70','Alcohol AL70','Químicos','Thames · bidón x 5 Lts · sugerido para gimnasio','bidón x 5 Lts','assets/materials/alcohol-al70.svg',1.0,100,true),
  ('bolsas-negras-45-60','Bolsas negras 45x60','Bolsas','Paquete de bolsas de residuos color negro','paquete','assets/materials/bolsas-negras-45-60.svg',1.0,110,true),
  ('bolsas-verdes-45-60','Bolsas verdes 45x60','Bolsas','Paquete de bolsas de residuos color verde','paquete','assets/materials/bolsas-verdes-45-60.svg',1.0,120,true),
  ('bolsas-negras-70-50','Bolsas negras 70x50','Bolsas','Paquete de bolsas de residuos color negro','paquete','assets/materials/bolsas-negras-70-50.svg',1.0,130,true),
  ('bolsas-verdes-70-50','Bolsas verdes 70x50','Bolsas','Paquete de bolsas de residuos color verde','paquete','assets/materials/bolsas-verdes-70-50.svg',1.0,140,true),
  ('bolsas-negras-90-110','Bolsas negras 90x110','Bolsas','Paquete de bolsas de residuos color negro','paquete','assets/materials/bolsas-negras-90-110.svg',1.0,150,true),
  ('bolsas-verdes-90-110','Bolsas verdes 90x110','Bolsas','Paquete de bolsas de residuos color verde','paquete','assets/materials/bolsas-verdes-90-110.svg',1.0,160,true),
  ('guantes-mapa-8','Guantes Mapa Talle 8','Elementos','Par de guantes','par','assets/materials/guantes-mapa-8.svg',1.0,170,true),
  ('balde-reforzado','Balde reforzado','Elementos','10 Lts','unidad','assets/materials/balde-reforzado.svg',1.0,180,true),
  ('pulverizador-gatillo','Pulverizador de 1 Lt + Gatillo','Elementos','Botella pulverizadora completa','unidad','assets/materials/pulverizador-gatillo.svg',2.0,190,true),
  ('medidor','Medidor','Elementos','Para dosificación de productos','unidad','assets/materials/medidor.svg',1.0,200,true),
  ('embudo-mediano','Embudo mediano','Elementos','Para trasvase controlado','unidad','assets/materials/embudo-mediano.svg',1.0,210,true),
  ('escoba-cabo','Escoba + Cabo metálico','Utensilios','Kit completo','unidad','assets/materials/escoba-cabo.svg',2.0,220,true),
  ('escobillon-cochera','Escobillón largo base madera + Cabo metálico','Utensilios','Para servicios con cochera','unidad','assets/materials/escobillon-cochera.svg',1.0,230,true),
  ('pala-cabo','Pala + Cabo metálico','Utensilios','Kit completo','unidad','assets/materials/pala-cabo.svg',1.0,240,true),
  ('secador-cabo','Secador + Cabo metálico','Utensilios','Kit completo','unidad','assets/materials/secador-cabo.svg',1.0,250,true),
  ('trapo-piso','Trapo de piso','Paños y fibras','Uso operativo general','unidad','assets/materials/trapo-piso.svg',2.0,260,true),
  ('rejilla','Rejilla','Paños y fibras','Uso operativo general','unidad','assets/materials/rejilla.svg',2.0,270,true),
  ('microfibra','Microfibra','Paños y fibras','Uso operativo general','unidad','assets/materials/microfibra.svg',2.0,280,true),
  ('fibra-verde','Fibra verde','Paños y fibras','Uso operativo general','unidad','assets/materials/fibra-verde.svg',2.0,290,true),
  ('esponja-acero','Esponja acero inoxidable','Paños y fibras','Uso operativo específico','unidad','assets/materials/esponja-acero.svg',2.0,300,true),
  ('esponja-amarilla','Esponja amarilla','Paños y fibras','Uso operativo general','unidad','assets/materials/esponja-amarilla.svg',2.0,310,true),
  ('plumero-microfibra','Plumero microfibra','Utensilios','Para superficies y altura baja','unidad','assets/materials/plumero-microfibra.svg',1.0,320,true),
  ('ballerina','Ballerina','Paños y fibras','Uso operativo general','unidad','assets/materials/ballerina.svg',2.0,330,true),
  ('kit-vidrios','Corderito + Secador + Agarre secador','Vidrios y altura','Kit para limpieza de vidrios','kit','assets/materials/kit-vidrios.svg',1.0,340,true),
  ('globo-telaranas','Globo para telarañas + cabo telescópico','Vidrios y altura','Cabo telescópico 2 + 2 metros','unidad','assets/materials/globo-telaranas.svg',1.0,350,true)
on conflict(slug) do update set name=excluded.name,category=excluded.category,detail=excluded.detail,unit=excluded.unit,image_url=excluded.image_url,suggested_quantity=excluded.suggested_quantity,sort_order=excluded.sort_order,active=excluded.active;
